### 회원 가입

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "kimkim3",
  "password": "helloworld"
}

### 로그인
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "kimkim1",
  "password": "helloworld"
}

> {% client.global.set("token", response.body.accessToken); %}

### 테스트
POST http://localhost:3000/auth/test
Authorization: Bearer {{token}}