### 로그인
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "kimkim2",
  "password": "helloworld"
}

> {% client.global.set("token", response.body.accessToken); %}


### 조회조건 없이 전체 검색
GET http://localhost:3000/boards
Authorization: Bearer {{token}}

### 생성
POST http://localhost:3000/boards
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "제목입니다",
  "description": "설명입니다.2"
}

> {% client.global.set("boardId", response.body.id); %}

### 단건 조회
GET http://localhost:3000/boards/{{boardId}}
Authorization: Bearer {{token}}


### 게시물 상태 변경
PATCH http://localhost:3000/boards/{{boardId}}/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "PRIVATE"
}

### 삭제
DELETE http://localhost:3000/boards/{{boardId}}
Authorization: Bearer {{token}}